# -*- coding: utf-8 -*-
"""ДЗ5_Кравченко Сергій.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdRROvQqJAX9kj3e5UuCd0l1-kwX_taj

### Завдання 1

Виконай диференціювання функції та знайди значення похідних у точках $x = 1$ і $x = -1/2$. Розв’яжи програмно та аналітично.

\
1. $\frac{x^3}{3} + \frac{x^2}{2} - 2x$  

\
2. $\sqrt{x^2 + 1}$  

\
3. $\frac{1}{\sqrt{x^2 + 1}}$



## Аналітичне розв'язання

### **Функція 1**:  
$f(x) = \frac{x^3}{3} + \frac{x^2}{2} - 2x$

#### Крок 1: Знаходимо похідну функції $f(x)$

Диференціюємо кожний доданок окремо:
- $\frac{d}{dx}\left(\frac{x^3}{3}\right) = \frac{1}{3} \cdot 3x^2 = x^2$
- $\frac{d}{dx}\left(\frac{x^2}{2}\right) = \frac{1}{2} \cdot 2x = x$
- $\frac{d}{dx}(-2x) = -2$

Похідна функції:  
$f'(x) = x^2 + x - 2$

#### Крок 2: Знаходимо значення похідної в точці $x = 1$

$f'(1) = (1)^2 + 1 - 2 = 1 + 1 - 2 = 0$

#### Крок 3: Знаходимо значення похідної в точці $x = -\frac{1}{2}$

Обчислюємо:  
$\left(-\frac{1}{2}\right)^2 = \frac{1}{4}$  

Підставляємо в похідну:
$f'\left(-\frac{1}{2}\right) = \frac{1}{4} - \frac{1}{2} - 2 = -\frac{9}{4} = - 2,25$

---

### **Функція 2**:  
$g(x) = \sqrt{x^2 + 1}$

#### Крок 1: Знаходимо похідну функції $g(x)$

Перепишемо функцію у вигляді степеня:  
$g(x) = (x^2 + 1)^{\frac{1}{2}}$  

Застосуємо правило ланцюга:
- Зовнішня функція: $u^{\frac{1}{2}}, \quad \frac{d}{dx} = \frac{1}{2} u^{-\frac{1}{2}}$
- Внутрішня функція: $u = x^2 + 1, \quad \frac{d}{dx} = 2x$

Похідна:  
$g'(x) = \frac{1}{2}(x^2 + 1)^{-\frac{1}{2}} \cdot 2x = \frac{x}{\sqrt{x^2 + 1}}$

#### Крок 2: Знаходимо значення похідної в точці $x = 1$

$g'(1) = \frac{1}{\sqrt{1^2 + 1}} = \frac{1}{\sqrt{2}} = \frac{\sqrt{2}}{2}$

#### Крок 3: Знаходимо значення похідної в точці $x = -\frac{1}{2}$

Обчислюємо знаменник:  
$\left(-\frac{1}{2}\right)^2 + 1 = \frac{1}{4} + 1 = \frac{5}{4} = \sqrt{\frac{5}{4}} = \frac{\sqrt{5}}{2}$  

Підставляємо в похідну:  
$g'\left(-\frac{1}{2}\right) = \frac{-\frac{1}{2}}{\frac{\sqrt{5}}{2}} = -\frac{1}{\sqrt{5}} = -\frac{\sqrt{5}}{5} = - 0,447$

---

### **Функція 3**:  
$h(x) = \frac{1}{\sqrt{x^2 + 1}}$

#### Крок 1: Знаходимо похідну функції $h(x)$

Перепишемо функцію у вигляді степеня:  
$h(x) = (x^2 + 1)^{-\frac{1}{2}}$  

Застосуємо правило ланцюга:
- Зовнішня функція: $u^{-\frac{1}{2}}, \quad \frac{d}{dx} = -\frac{1}{2} u^{-\frac{3}{2}}$
- Внутрішня функція: $u = x^2 + 1, \quad \frac{d}{dx} = 2x$

Похідна:  
$h'(x) = -\frac{1}{2}(x^2 + 1)^{-\frac{3}{2}} \cdot 2x = -\frac{x}{(x^2 + 1)^{\frac{3}{2}}}$

#### Крок 2: Знаходимо значення похідної в точці $x = 1$

Обчислюємо знаменник:  
$(1^2 + 1)^{\frac{3}{2}} = 2^{\frac{3}{2}} = 2\sqrt{2}$  

Підставляємо в похідну:  
$h'(1) = -\frac{1}{2\sqrt{2}} = -\frac{\sqrt{2}}{4}$

#### Крок 3: Знаходимо значення похідної в точці $x = -\frac{1}{2}$

Обчислюємо знаменник:  
$\left(\left(-\frac{1}{2}\right)^2 + 1\right)^{\frac{3}{2}} = \left(\frac{1}{4} + 1\right)^{\frac{3}{2}} = \left(\frac{5}{4}\right)^{\frac{3}{2}} = \frac{(\sqrt{5})^3}{2^3} = \frac{5\sqrt{5}}{8}$  

Підставляємо в похідну:  
$h'\left(-\frac{1}{2}\right) = -\frac{-\frac{1}{2}}{\frac{5\sqrt{5}}{8}} = \frac{4}{5\sqrt{5}} = \frac{4\sqrt{5}}{25} = 0,357$
"""

import sympy as sp

# Задаємо змінну
x = sp.symbols('x')

# Функція 1: f(x) = x^3/3 + x^2/2 - 2x
f = x**3 / 3 + x**2 / 2 - 2*x
f_prime = sp.diff(f, x)

# Значення похідної у точках x = 1 і x = -1/2
f_prime_at_1 = f_prime.subs(x, 1)
f_prime_at_neg_half = f_prime.subs(x, -1/2)

# Функція 2: g(x) = sqrt(x^2 + 1)
g = sp.sqrt(x**2 + 1)
g_prime = sp.diff(g, x)

# Значення похідної у точках x = 1 і x = -1/2
g_prime_at_1 = g_prime.subs(x, 1)
g_prime_at_neg_half = g_prime.subs(x, -1/2)

# Функція 3: h(x) = 1 / sqrt(x^2 + 1)
h = 1 / sp.sqrt(x**2 + 1)
h_prime = sp.diff(h, x)

# Значення похідної у точках x = 1 і x = -1/2
h_prime_at_1 = h_prime.subs(x, 1)
h_prime_at_neg_half = h_prime.subs(x, -1/2)

# Виведення результатів
print("Функція 1:")
print(f"f'(1) = {f_prime_at_1}")
print(f"f'(-1/2) = {f_prime_at_neg_half}")
print()

print("Функція 2:")
print(f"g'(1) = {g_prime_at_1}")
print(f"g'(-1/2) = {g_prime_at_neg_half}")
print()

print("Функція 3:")
print(f"h'(1) = {h_prime_at_1}")
print(f"h'(-1/2) = {h_prime_at_neg_half}")



"""###Завдання 2

Аналітично виконай диференціювання функції та знайди точку максимуму. Програмно візуалізуй функцію, її похідну та точку максимуму.

\
$y = -3x^2 + 30x.$

#Розвязання

## Крок 1: Визначення функції та її похідної

Задано функцію:  
$y = -3x^2 + 30x$  

Щоб знайти точки екстремуму, обчислюємо першу похідну:  
$y' = \frac{d}{dx}(-3x^2 + 30x) = -6x + 30$

---

### Крок 2: Пошук критичних точок

Критичні точки — це ті значення $x$, при яких перша похідна дорівнює нулю:  
$y' = -6x + 30 = 0$  

Розв'яжемо це рівняння:  
$-6x + 30 = 0 \quad \Rightarrow \quad -6x = -30 \quad \Rightarrow \quad x = 5$  

Таким чином, критична точка знаходиться при $x = 5$.

---

### Крок 3: Визначення характеру критичної точки

Щоб зрозуміти, чи є ця точка максимумом або мінімумом, обчислимо другу похідну функції:  
$y'' = \frac{d}{dx}(-6x + 30) = -6$  

Оскільки друга похідна $y'' = -6$ є від’ємною, це означає, що в точці $x = 5$ функція має **максимум**.

---

### Крок 4: Знаходження значення функції в точці максимуму

Підставимо $x = 5$ у початкову функцію, щоб обчислити $y$:  
$y = -3x^2 + 30x$  
$y = -3(5)^2 + 30(5) = -3 \cdot 25 + 150 = -75 + 150 = 75$  

Таким чином, максимальне значення функції дорівнює $y = 75$.

---

### Крок 5: Висновок

Функція $y = -3x^2 + 30x$ досягає максимуму при $x = 5$, і значення в цій точці дорівнює $y = 75$.  
Отже, точка максимуму — це $(5, 75)$.

---

### Додаткова візуалізація

На графіку можна побачити:
1. **Графік функції** $y = -3x^2 + 30x$.  
2. **Графік похідної** $y' = -6x + 30$.  
3. **Максимальну точку** $(5, 75)$, яка виділена червоною крапкою.

Цей підхід чітко демонструє зв'язок між аналітичним розв'язанням і графічним представленням результатів.

"""

import numpy as np
import matplotlib.pyplot as plt
from sympy import symbols, diff, solve

# Функція та її похідна
x = symbols('x')
y = -3*x**2 + 30*x
dy_dx = diff(y, x)
critical_points = solve(dy_dx, x)  # Вирішення dy/dx = 0 для пошуку точки максимуму

# Пошук максимуму
y_values_at_critical_points = [(point, y.subs(x, point)) for point in critical_points]
max_point = max(y_values_at_critical_points, key=lambda item: item[1])  # Знаходження максимумму

# Виведення x та y значення
x_max, y_max = max_point


x_values = np.linspace(0, 15, 500)
y_values = -3 * x_values**2 + 30 * x_values
dy_dx_values = -6 * x_values + 30

plt.figure(figsize=(10, 6))

# Візуалізація
plt.plot(x_values, y_values, label="y = -3x^2 + 30x", linewidth=2)


plt.plot(x_values, dy_dx_values, label="y' = -6x + 30", linestyle="--", linewidth=2)

# Максимальня точка
plt.scatter(float(x_max), float(y_max), color='red', label=f"Maximum Point ({x_max}, {y_max})", zorder=5)


plt.title("Function, Derivative, and Maximum Point")
plt.xlabel("x")
plt.ylabel("y")
plt.axhline(0, color='black', linewidth=0.5, linestyle="--")
plt.axvline(0, color='black', linewidth=0.5, linestyle="--")
plt.legend()
plt.grid(True)


plt.show()

# Вивід результату
x_max, y_max

"""### Висновок

Функція $y = -3x^2 + 30x$ досягає максимуму при $x = 5$, і значення в цій точці дорівнює $y = 75$.  
Отже, точка максимуму — це $(5, 75)$.
"""